version: '2'

services:
  apidotnet:
    image: stevelasker/api-dotnet
  webnode:
    image: stevelasker/web-node
    ports:
      - "3000:3000"
    environment:
      - HTTPPORT=3000
      - APIPORT=5000
      - APIURL=apidotnet
